apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cifar10-data
  namespace: ml-training
  labels:
    app.kubernetes.io/part-of: mlops-pytorch-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-checkpoints
  namespace: ml-training
  labels:
    app.kubernetes.io/part-of: mlops-pytorch-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
